language: rust
env:
  global:
    - secure: b/kIRK9PnIaZCU7AY4k9Fw6CXSWOtoyCnWsjBiIsZY9yP+MN8b18PO4ZKwDlQwdje0qNHy44e7VjSng2Bn7eOBcl/H85wjyfolFF7EpJEOZQdT1f3A4zlzKdcuHKPrFpKG/UV7cEj72dtSkuzVHfAaS3k69mYz7dTgu6M9+zbAY=
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
