[package]
name = "mersenne_twister"
version = "0.3.0"
authors = ["David Creswick <dcrewi@gyrae.net>"]
license = "Apache-2.0"
description = "Mersenne Twister pseudorandom number generator"
repository = "https://github.com/dcrewi/rust-mersenne-twister"
documentation = "https://dcrewi.github.io/rust-mersenne-twister/doc/0.3/mersenne_twister/index.html"
readme = "README.md"
keywords = ["random", "rng", "algorithm", "mersenne"]

[dependencies]
rand = "0.3"
